### ISSUE TITLE
Obscure error message and core dump when PLL instance can't be routed

### ISSUE THREAD

**Issue by tomverbeure** [cseed/arachne-pnr#100]
```	arachne-pnr -d 8k -P tq144:4k -p blackice-ii.pcf chip.blif -V post_place.v -o chip.txt```

The error message:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

The design mistake is that the input clock of a SB_PLL40_2F_PAD PLL is also used to clock a FF directly. Arachne should flag this as illegal.

Example attached.

[issue.zip](https://github.com/cseed/arachne-pnr/files/1822210/issue.zip)

**Comment by daveshah1** [comment]
Thanks for reporting this. At some point it would be nice to produce better error messages for all placement and routing failures.

**Comment by tomverbeure** [comment]
@ducky64,
I think your case is different than what I reported in that my case was a broken error warning, but the input design was indeed wrong.

In your case, the design seems to be correct yet it’s still bombing. That’s worse.

I suggest that you file a separate issue for this, so that it may get more attention (which it deserves.)

Tom

**Comment by tomverbeure** [comment]
This issue is a dup of issue #77 and can be closed.
