### ISSUE TITLE
void Model::check(const Design*) const: Assertion `!p2->is_bidir()' failed

### ISSUE THREAD

**Issue by whitequark** [cseed/arachne-pnr#113]
Non-reduced repro: [glasgow_j2mnk25q.zip](https://github.com/cseed/arachne-pnr/files/1993601/glasgow_j2mnk25q.zip).
It's caused by the clock signal.

**Comment by daveshah1** [comment]
As in #114, it looks like you are trying to use an IO both before and after a SB_GB_IO, which is not legal. Use the D_IN_0 output of the SB_GB_IO for this purpose.

**Comment by whitequark** [comment]
Yes, I know it's not a legal design, but it shouldn't die with an assertion failure.

**Comment by daveshah1** [comment]
That's fine, I agree with that. I will keep the bug open then.

**Comment by daveshah1** [comment]
I realise this is actually a duplicate of #77.

**Comment by whitequark** [comment]
Ah, thanks for triaging.
