### ISSUE TITLE
SB_IO and SB_GB_IO PACKAGE_PIN connected to the same port cause fatal error

### ISSUE THREAD

**Issue by whitequark** [cseed/arachne-pnr#114]
Non-reduced testcase: [glasgow_6kkz18rn.zip](https://github.com/cseed/arachne-pnr/files/1993609/glasgow_6kkz18rn.zip). Caused by clk_if port.

Also, the error message points at the end of blif and is thus useless.

**Comment by daveshah1** [comment]
This is not a legal design as far as I know. SB_GB_IO has all of the ports and parameters of SB_IO too, and they should be used instead of adding another SB_IO.

**Comment by whitequark** [comment]
You're right. Sorry for the noise.
