### ISSUE TITLE
Add tags for release versions

### ISSUE THREAD

**Issue by mithro** [cseed/arachne-pnr#117]
It would be good if tags were on this repository for releases.

**Comment by cliffordwolf** [comment]
There hasn't been a single arachne-pnr release yet. Therefore all releases are already tagged.

**Comment by mithro** [comment]
Can you tag the first commit v0.0 then?

**Comment by whitequark** [comment]
That seems just confusing.

**Comment by mithro** [comment]
`git describe` currently fails because there are not tags to describe from. Adding `v0.0` at the first commit means that you get a useful `git describe` output which can then be used for packaging.
