### ISSUE TITLE
feature request: version query

### ISSUE THREAD

**Issue by jamesbowman** [cseed/arachne-pnr#13]
yosys has a nice feature:

```
$ yosys -V
Yosys 0.5+352 (git sha1 5dd3e93, gcc 4.6.3-1ubuntu5 -fPIC -Os)
```

Which is nice for quickly confirming installed version. Would it be possible to implement something similar for archne-pnr?

**Comment by cseed** [comment]
Yep!  I will add this.

**Comment by cseed** [comment]
Done.  I mostly copied yosys:

```
$ arachne-pnr -v
arachne-pnr 0.1+103+2 (git sha1 efdb026, c++ 7.0.0 -O2)
```

but +2 here means that there are 2 modified (staged or unstaged) tracked files.  I also output the version string in all arachne-pnr generated files (.txt, .pcf, etc.)  Thanks for the suggestion!
