### ISSUE TITLE
PLLs: terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by cliffordwolf** [cseed/arachne-pnr#17]
The following BLIF file

    .model c3demo
    .inputs CLK12MHZ
    .outputs CLKOUT
    .names $false
    .names $true
    1
    .names $undef
    .gate SB_PLL40_CORE BYPASS=$false DYNAMICDELAY[0]=$false DYNAMICDELAY[1]=$false DYNAMICDELAY[2]=$false DYNAMICDELAY[3]=$false DYNAMICDELAY[4]=$false DYNAMICDELAY[5]=$false DYNAMICDELAY[6]=$false DYNAMICDELAY[7]=$false EXTFEEDBACK=$false LATCHINPUTVALUE=$false LOCK=pll_lock PLLOUTCORE=PLLOUTCORE PLLOUTGLOBAL=clk REFERENCECLK=CLK12MHZ RESETB=$true
    .attr src "c3demo.v:34"
    .param DELAY_ADJUSTMENT_MODE_FEEDBACK "FIXED"
    .param DELAY_ADJUSTMENT_MODE_RELATIVE "FIXED"
    .param DIVF 00000000000000000000000000000000
    .param DIVQ 00000000000000000000000000000001
    .param DIVR 00000000000000000000000000001010
    .param ENABLE_ICEGATE 00000000000000000000000000000000
    .param FDA_FEEDBACK 00000000000000000000000000000000
    .param FDA_RELATIVE 00000000000000000000000000000000
    .param FEEDBACK_PATH "SIMPLE"
    .param FILTER_RANGE 00000000000000000000000000000000
    .param PLLOUT_SELECT "GENCLK"
    .param TEST_MODE 00000000000000000000000000000000
    .names clk CLKOUT
    1 1
    .end

and the following PCF file

    set_io CLK12MHZ R9
    set_io CLKOUT P14

Produce the following error:

    $ arachne-pnr -d 8k -p test.pcf test.blif 
    seed: 1
    ...
    place_constraints...
    terminate called after throwing an instance of 'std::out_of_range'
      what():  map::at
    Aborted

**Comment by cseed** [comment]
Fixed: https://github.com/cseed/arachne-pnr/commit/4fc66f758f830ffd57de69aa6520c2a65757d08c
