### ISSUE TITLE
Consider more permissive open source licensing

### ISSUE THREAD

**Issue by scanlime** [cseed/arachne-pnr#23]
Hello! I'm working on an open source library which will be generating FPGA bitstreams dynamically, using yosys + icestorm + arachne-pnr. If you'd like more info about what I'm doing, here's the site: https://github.com/scanlime/wiggleport

I was wondering if you would consider re-releasing arachne-pnr under a more permissive license that would allow it to be integrated into other software packages? Something similar to the MIT or ISC license would be ideal, but even LGPL would be a step forward.

Thank you for your consideration!

**Comment by cliffordwolf** [comment]
I second that.

Especially in non-Linux embedded applications (running on OSes like Contiki or BitThunder) it might be necessary to link everything in one binary. GPL can be a showstopper in such cases.

**Comment by drom** [comment]
I am building my JavaScript based UI, and using ASM.JS version YosysJS. MIT would be perfect for that.

**Comment by cliffordwolf** [comment]
Thanks!
