### ISSUE TITLE
intermittent fatal error during placement

### ISSUE THREAD

**Issue by RGD2** [cseed/arachne-pnr#27]
Hi cseed, 

Thanks ever so much for arachne-pnr!

with latest arachne-pnr@1a4fdf9 
as detailed in jamesbowman/swapforth#27 , the error is:

```
place...
fatal error: failed to place: placed 1121 LCs of 1220 / 1280
```

Any suggestions appreciated

**Comment by RGD2** [comment]
This seems to be an intermittent failure - it can fail if rerun several times in a row, and then suddenly work.

**Comment by cseed** [comment]
Working now, see https://github.com/jamesbowman/swapforth/issues/27.
