### ISSUE TITLE
Handling of LVDS pin constraint

### ISSUE THREAD

**Issue by mo101** [cseed/arachne-pnr#37]
A minor thing: if an LVDS pin is specified in the .pcf file as the "wrong" one of its pair, arachne-pnr aborts with

```
arachne-pnr: src/place.cc:1063: void Placer::place_initial(): Assertion `valid(chipdb->cell_location[c].tile())' failed.
```

rather than producing an error message or (perhaps preferably) correctly allocating both pins. To demonstrate this, take the example in the issue report "Apparently invalid bitstream for LVDS input" and change the pin assignment in the first line of the constraints file from 34 to 33.

**Comment by cliffordwolf** [comment]
Fixed by #97.
