### ISSUE TITLE
Fix Cygwin build

### ISSUE THREAD

**Issue by yugr** [cseed/arachne-pnr#41]
Cygwin build currently fails due to minor issues. Attached patch seems to fix those (reproduced and tested on Clifford's clone of arachne-pnr).

[0001-arachne-pnr-Fix-Cygwin-build.patch.txt](https://github.com/cseed/arachne-pnr/files/405742/0001-arachne-pnr-Fix-Cygwin-build.patch.txt)

**Comment by cseed** [comment]
Created a PR: https://github.com/cseed/arachne-pnr/pull/42.  Will merge in after the automated tests check out.  Thanks for the patch!

**Comment by cseed** [comment]
Merged.
