### ISSUE TITLE
Output JSON file

### ISSUE THREAD

**Issue by drom** [cseed/arachne-pnr#47]
I am working on rendering engine that would produce SVG image of the FPGA array with logic functions and connections between them. I know that yosys is capable of producing result in JSON format, that is greatly simplifies further processing. Would it be possible to emit PNR information in JSON format from arachne-pnr?

**Comment by cliffordwolf** [comment]
You could write a post-place netlist as BLIF file with `arachne-pnr --post-place-blif netlist.blif` and then convert it to JSON using Yosys with `yosys -q -o netlist.json netlist.blif`.

**Comment by drom** [comment]
@cliffordwolf yes, you are right. That works.
